import { utils } from '~utils/index';

export { AddToCart } from '~components/AddToCart/AddToCart';
export * from '~components/Buttons';
export { Cart } from '~components/Cart/Cart';
export { CartItem } from '~components/CartItem/CartItem';
export { CTA } from '~components/CTA/CTA';
export { Counter } from '~components/Counter/Counter';
export { LeftDrawer } from '~components/LeftDrawer/LeftDrawer';
export { Dropdown } from '~components/Dropdown/Dropdown';
export { FancyImageBox } from '~components/FancyImageBox/FancyImageBox';
export { Image } from '~components/Image/Image';
export { Link } from '~components/Link/Link';
export { Logo } from '~components/Logo/Logo';
export { Menu } from '~components/Menu/Menu';
export { Modal } from '~components/Modal/Modal';
export { Navigation } from '~components/Navigation/Navigation';
export { NewsletterBlock } from '~components/NewsletterBlock/NewsletterBlock';
export { PageFooter } from '~components/PageFooter/PageFooter';
export { PaymentMethods } from '~components/PaymentMethods/PaymentMethods';
export { Price } from '~components/Price/Price';
export { Portal } from '~components/Portal/Portal';
export { ProductVariants } from '~components/ProductVariants/ProductVariants';
// export { MenuMain } from '~components/MenuMain/MenuMain';
export { SearchBar } from '~components/SearchBar/SearchBar';
export { SocialBlock } from '~components/SocialBlock/SocialBlock';
export { Swiper } from '~components/Swiper/Swiper';
export { TextBlock } from '~components/TextBlock/TextBlock';

// export * from '~components/Tiles/Tiles';
